export const ITEMS = [
  {
    id: "i_01",
    name: "Espresso Shot",
    rarity: "common",
    icon: "☕",
    effect: "+10% Move Speed",
  },
  {
    id: "i_02",
    name: "Dumbbell",
    rarity: "common",
    icon: "🏋️",
    effect: "+10 Base Damage",
  },
  {
    id: "i_03",
    name: "Scope",
    rarity: "common",
    icon: "🔭",
    effect: "+15% Range",
  },
  {
    id: "i_04",
    name: "Extended Mag",
    rarity: "common",
    icon: "🔋",
    effect: "+20% Duration",
  },
  {
    id: "i_05",
    name: "Thick Skin",
    rarity: "common",
    icon: "🦏",
    effect: "-5 Damage Taken",
  },
  {
    id: "i_06",
    name: "Magnet",
    rarity: "common",
    icon: "🧲",
    effect: "+30% Pickup Range",
  },
  {
    id: "i_07",
    name: "Piggy Bank",
    rarity: "common",
    icon: "🐖",
    effect: "+1 Interest on Gold per wave",
  },
  {
    id: "i_08",
    name: "Band-Aid",
    rarity: "common",
    icon: "🩹",
    effect: "+1 HP Regen/sec",
  },
  {
    id: "i_09",
    name: "Energy Drink",
    rarity: "common",
    icon: "🥤",
    effect: "+5% Haste",
  },
  {
    id: "i_10",
    name: "LED Strip",
    rarity: "common",
    icon: "💡",
    effect: "Projectiles glow (Light radius)",
  },
  {
    id: "i_11",
    name: "Rubber Ball",
    rarity: "uncommon",
    icon: "🎾",
    effect: "+1 Bounce",
  },
  {
    id: "i_12",
    name: "Vampire Fangs",
    rarity: "uncommon",
    icon: "🧛",
    effect: "Heal 1HP per 100 dmg dealt",
  },
  {
    id: "i_13",
    name: "Ghost Pepper",
    rarity: "uncommon",
    icon: "🌶️",
    effect: "Deal fire dmg on contact",
  },
  {
    id: "i_14",
    name: "Mirror Shield",
    rarity: "uncommon",
    icon: "🛡️",
    effect: "Reflect 50% dmg back to attacker",
  },
  {
    id: "i_15",
    name: "Recycling Bin",
    rarity: "uncommon",
    icon: "♻️",
    effect: "Rerolls cost 50% less",
  },
  {
    id: "i_16",
    name: "Battery Pack",
    rarity: "uncommon",
    icon: "🔋",
    effect: "-15% Item Cooldowns",
  },
  {
    id: "i_17",
    name: "Target HUD",
    rarity: "uncommon",
    icon: "🎯",
    effect: "Show enemy HP bars + 10% Crit",
  },
  {
    id: "i_18",
    name: "Splitter",
    rarity: "uncommon",
    icon: "✂️",
    effect: "Split shot on hit",
  },
  {
    id: "i_19",
    name: "Hourglass",
    rarity: "uncommon",
    icon: "⏳",
    effect: "Enemies are 10% slower",
  },
  {
    id: "i_20",
    name: "Lucky Clover",
    rarity: "uncommon",
    icon: "🍀",
    effect: "+20 Luck",
  },
  {
    id: "i_21",
    name: "Glass Cannon",
    rarity: "rare",
    icon: "🍷",
    effect: "3x Damage, Max HP = 1",
  },
  {
    id: "i_22",
    name: "Executioner Hood",
    rarity: "rare",
    icon: "💀",
    effect: "Kill enemies under 15% HP",
  },
  {
    id: "i_23",
    name: "Explosive Tips",
    rarity: "rare",
    icon: "🧨",
    effect: "All shots explode on impact",
  },
  {
    id: "i_24",
    name: "Berserker Helm",
    rarity: "rare",
    icon: "👹",
    effect: "+1% Dmg for every 1% missing HP",
  },
  {
    id: "i_25",
    name: "Chaos Emerald",
    rarity: "rare",
    icon: "💎",
    effect: "Switch element every 10s",
  },
  {
    id: "i_26",
    name: "The Investment",
    rarity: "rare",
    icon: "📈",
    effect: "-50% Dmg now, +10% per wave (Infinite)",
  },
  {
    id: "i_27",
    name: "Second Heart",
    rarity: "rare",
    icon: "❤️",
    effect: "Revive once with 50% HP",
  },
  {
    id: "i_28",
    name: "Smart Bomb",
    rarity: "rare",
    icon: "💣",
    effect: "Taking dmg clears screen (60s CD)",
  },
  {
    id: "i_29",
    name: "Holo-Decoy",
    rarity: "rare",
    icon: "👻",
    effect: "Spawns decoy that attracts fire",
  },
  {
    id: "i_30",
    name: "Time Dilator",
    rarity: "rare",
    icon: "🐌",
    effect: "Enemy projectiles move 50% slower",
  },
  {
    id: "i_31",
    name: "The Printer",
    rarity: "legendary",
    icon: "🖨️",
    effect: "Duplicate your highest lvl weapon",
  },
  {
    id: "i_32",
    name: "God Mode",
    rarity: "legendary",
    icon: "👑",
    effect: "Invincible for 2s after kill",
  },
  {
    id: "i_33",
    name: "Black Hole",
    rarity: "legendary",
    icon: "⚫",
    effect: "Boss death sucks all XP to player",
  },
  {
    id: "i_34",
    name: "Infinite Ammo",
    rarity: "legendary",
    icon: "♾️",
    effect: "-80% Cooldowns",
  },
  {
    id: "i_35",
    name: "Midas Touch",
    rarity: "legendary",
    icon: "✋",
    effect: "Enemies turn to gold (Insta-kill + money)",
  },
  {
    id: "i_36",
    name: "Cursed Eye",
    rarity: "cursed",
    icon: "👁️",
    effect: "+100% Crit, Blind (Dark Screen)",
  },
  {
    id: "i_37",
    name: "Heavy Shackles",
    rarity: "cursed",
    icon: "⛓️",
    effect: "Can't move, +200% Range & Armor",
  },
  {
    id: "i_38",
    name: "Pacifist Chip",
    rarity: "cursed",
    icon: "☮️",
    effect: "You deal 0 dmg. Pets deal 1000% dmg.",
  },
  {
    id: "i_39",
    name: "Debt",
    rarity: "cursed",
    icon: "💸",
    effect: "-1000 Gold start, +100 Luck",
  },
  {
    id: "i_40",
    name: "Glitch God",
    rarity: "cursed",
    icon: "👾",
    effect: "Randomize all weapons every 10s",
  },
];
